spring:
  application:
    name: user-service
  flyway:
    schemas: users
    default-schema: users
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=users
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver