spring:
  application:
    name: app-launcher

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bank-db?currentSchema=users
    username: ${DB_USER}
    password: ${DB_PASS}

  flyway:
    schemas: users
    locations: classpath:db/migration

  jwt:
    secret: ${JWT_SECRET}

server:
  port: 8080
  address: 0.0.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs